Statically compile grml-runtty to avoid dependency on unstable's libc
It's annoying if grml-scripts can't be updated any longer on
systems based for example on Debian/wheezy, so let's get rid
of the dependency on libc.

Compiling requires -lcompat, otherwise fails with:

| undefined reference to `clearenv'